# General
spring:
  application:
    name: api-email-sender
logbook:
  body-filters:
    json-path:
      - key: "$.htmlMessage"
        value: '[base64]'
      - key: "$.attachments[*].content"
        value: '[base64]'
# OpenAPI
openapi:
  name: api-service-email-sender
  version: '@project.version@'
  title: EmailSender

# SMTP properties
integration:
  email:
    default-properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          allow8bitmime: true
        mime:
          charset: UTF-8
