openapi: 3.0.1
info:
  title: EmailSender
  contact: {}
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: "1.1"
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Email resources
  description: Resources for sending emails
paths:
  /send/email:
    post:
      tags:
      - Email resources
      summary: Send an e-mail
      operationId: sendMail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEmailRequest'
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Problem'
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                oneOf:
                - $ref: '#/components/schemas/Problem'
                - $ref: '#/components/schemas/ConstraintViolation'
        "200":
          description: Successful Operation
  /api-docs:
    get:
      tags:
      - API
      summary: OpenAPI
      operationId: getApiDocs
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-mutual-ssl: Optional
components:
  schemas:
    Attachment:
      required:
      - contentType
      - name
      type: object
      properties:
        content:
          type: string
          description: The attachment (file) content as a BASE64-encoded string
          example: aGVsbG8gd29ybGQK
        name:
          type: string
          description: The attachment filename
          example: test.txt
        contentType:
          type: string
          description: The attachment content type
          example: text/plain
      description: E-mail attachment
    SendEmailRequest:
      required:
      - emailAddress
      - sender
      - subject
      type: object
      properties:
        emailAddress:
          type: string
          description: Recipient e-mail address
          example: recipient@recipient.se
        subject:
          type: string
          description: E-mail subject
        message:
          type: string
          description: E-mail plain-text body
        htmlMessage:
          type: string
          description: E-mail HTML body (BASE64-encoded)
        sender:
          $ref: '#/components/schemas/Sender'
        attachments:
          type: array
          description: Attachments
          items:
            $ref: '#/components/schemas/Attachment'
        headers:
          type: object
          additionalProperties:
            type: array
            description: Headers
            items:
              type: string
              description: Headers
          description: Headers
      description: Send e-mail request
    Sender:
      required:
      - address
      - name
      type: object
      properties:
        name:
          type: string
          description: The sender of the e-mail
        address:
          type: string
          description: Sender e-mail address
          example: sender@sender.se
        replyTo:
          type: string
          description: Reply-to e-mail address
          example: sender@sender.se
      description: E-mail sender
    Problem:
      type: object
      properties:
        instance:
          type: string
          format: uri
        type:
          type: string
          format: uri
        parameters:
          type: object
          additionalProperties:
            type: object
        status:
          $ref: '#/components/schemas/StatusType'
        detail:
          type: string
        title:
          type: string
    StatusType:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        reasonPhrase:
          type: string
    ConstraintDescriptorObject:
      type: object
      properties:
        annotation:
          type: object
        attributes:
          type: object
          additionalProperties:
            type: object
        reportAsSingleViolation:
          type: boolean
        validationAppliesTo:
          type: string
          enum:
          - IMPLICIT
          - RETURN_VALUE
          - PARAMETERS
        composingConstraints:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ConstraintDescriptorObject'
        valueUnwrapping:
          type: string
          enum:
          - DEFAULT
          - UNWRAP
          - SKIP
        messageTemplate:
          type: string
    ConstraintViolation:
      type: object
      properties:
        message:
          type: string
        messageTemplate:
          type: string
        propertyPath:
          $ref: '#/components/schemas/Path'
        rootBean:
          type: object
        constraintDescriptor:
          $ref: '#/components/schemas/ConstraintDescriptorObject'
        invalidValue:
          type: object
        leafBean:
          type: object
        executableReturnValue:
          type: object
        executableParameters:
          type: array
          items:
            type: object
    Path:
      type: object
  securitySchemes: {}
