version: '3'
services:
  ms-email-sender-sandbox:
    container_name: ms-email-sender-sandbox
    image: 'evil.sundsvall.se/ms-email-sender:latest'
    network_mode: bridge
    restart: always
    depends_on:
      - ms-email-sender-sandbox-smtp-server
    links:
      - ms-email-sender-sandbox-smtp-server:smtp-server
    ports:
      - '9051:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=sandbox

      - SMTP_HOST=smtp-server
      - SMTP_PORT=25

  ms-email-sender-sandbox-smtp-server:
    container_name: ms-email-sender-sandbox-smtp-server
    image: rnwood/smtp4dev:prerelease
    network_mode: bridge
    restart: always
    expose:
      - '25'

