spring:
  main:
    banner-mode: 'off'

# Intentionally empty, since they are set dynamically when the mailpit Testcontainer is started
integration:
  email:
    instances:
      2281:
        host:
        port:
